- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable and start logstash
  ansible.builtin.systemd:
    name: logstash 
    state: started 
    enabled: yes
  register: logstash_service