---

- name: CA exists
  stat:
    path: "{{  logstash_certs_dir }}/{{ elasticsearch_ca_chain_name }}"
  register: elastic_ca_file

- shell: uname -s
  register: unames
  changed_when: false

- shell: uname -m
  register: unamem
  changed_when: false

- name: add elk group 
  ansible.builtin.group:
    name: "{{ logstash_user }}"
    state: present

- name: add elk user
  ansible.builtin.user:
    name: "{{ logstash_user }}"
    shell: /bin/sh
    password: "*"
    group: "{{ logstash_group }}"

- name: is logstash installed
  stat:
    path: "{{ logstash_extract_dir }}/logstash-{{ logstash_version }}"
  register: logstash_dir

- name: Download and extract logstash
  ansible.builtin.unarchive:
    src: https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-{{ unames.stdout | lower }}-{{ unamem.stdout }}.tar.gz
    dest: "{{ logstash_extract_dir }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    remote_src: yes
  when: 
    - not logstash_dir.stat.exists
    - logstash_install_mode == 'http'

- ansible.builtin.fail:
    msg: elasticsearch_install_mode set to local but no elasticsearch_local_tar_path specified
  when:
    - not logstash_dir.stat.exists
    - logstash_install_mode == 'local'
    - logstash_local_tar_path == ''

- name: Extract logstash
  ansible.builtin.unarchive:
    src: "{{ logstash_local_tar_path }}/logstash-{{ logstash_version }}-{{ unames.stdout | lower }}-{{ unamem.stdout }}.tar.gz"
    dest: "{{ logstash_extract_dir }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  when: 
    - not logstash_dir.stat.exists
    - logstash_install_mode == 'local'

- include_tasks: 
    file: keystore_setup.yml
  when: elasticsearch_security_enabled

- include_role:
    name: https
  when:
    - elasticsearch_https_enabled
    # TODO: Security enabled, nodes require TLS regardless of https_enabled?
    - generateca is not defined or not generateca
    - https_complete is not defined

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  loop:
    - "{{ logstash_conf_dir }}"
    - "{{ logstash_log_dir }}"
    - "{{ logstash_pid_dir }}"
    - "{{ logstash_data_dir }}"
    - "{{ logstash_certs_dir }}"
    - "{{ logstash_certs_dir }}/ca"
    - "{{ logstash_conf_dir }}/patterns"
    - "{{ logstash_conf_dir }}/conf.d"
    - "{{ logstash_conf_dir }}/conf.d/pipelines"
    - "{{ logstash_conf_dir }}/scripts"

- name: Fix directory permission
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    recurse: yes
    mode: u=rwX,g=rX,o=r
  loop:
    - "{{ logstash_conf_dir }}"
    - "{{ logstash_log_dir }}"
    - "{{ logstash_pid_dir }}"
    - "{{ logstash_data_dir }}"
    - "{{ logstash_certs_dir }}"

- name: create symlink to logstash
  ansible.builtin.file:
    src: "{{ logstash_extract_dir }}/logstash-{{ logstash_version }}"
    dest: "{{ logstash_extract_dir }}/logstash"
    state: link
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"

- name: Render logstash env file
  ansible.builtin.template:
    src: logstash_env.j2
    dest: "{{ logstash_env_file[ansible_os_family] }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - check if logstash is active
    - restart logstash

- name: Render logstash service file
  ansible.builtin.template:
    src: logstash.service.j2
    dest: /etc/systemd/system/logstash.service
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - reload systemd
    - check if logstash is active
    - restart logstash

- name: Copy elastic CA
  ansible.builtin.copy:
    src: "{{ elasticsearch_local_certs_dir }}/ca/{{ elasticsearch_ca_chain_name }}"
    dest: "{{ logstash_certs_dir }}/ca/{{ elasticsearch_ca_chain_name }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  when: 
    - elasticsearch_https_enabled
    - not elastic_ca_file.stat.exists or elastic_ca_file.stat.checksum != (lookup('file', elasticsearch_local_certs_dir + "/" + elasticsearch_ca_chain_name) | hash('sha256'))
  notify:
    - check if logstash is active
    - restart logstash

- name: Find additional Intermediate CAs
  ansible.builtin.find:
    paths: "{{ elasticsearch_local_certs_dir }}/ca/intermediates"
    patterns: "*"
  register: intermediate_files
  when: elasticsearch_https_enabled
  delegate_to: localhost

- name: Intermediate files
  debug:
    var: intermediate_files

- name: Copy additional Intermediate CAs
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ logstash_certs_dir }}/ca/{{ item.path | basename }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  loop: "{{ intermediate_files.files }}"
  when: elasticsearch_https_enabled
  notify:
    - check if logstash is active
    - restart logstash

- name: Find additional Root CAs
  ansible.builtin.find:
    paths: "{{ elasticsearch_local_certs_dir }}/ca/roots"
    patterns: "*"
  register: root_files
  when: elasticsearch_https_enabled
  delegate_to: localhost

- name: Root files
  debug:
    var: root_files

- name: Copy additional Root CAs
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ logstash_certs_dir }}/ca/{{ item.path | basename }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  loop: "{{ root_files.files }}"
  when: elasticsearch_https_enabled
  notify:
    - check if logstash is active
    - restart logstash

- name: Check logstash SSL cert exists
  stat:
    path: "{{ logstash_certs_dir }}/{{ logstash_ssl_cert_name }}"
  register: logstash_ssl_cert

- name: Check logstash SSL key exists
  stat:
    path: "{{ logstash_certs_dir }}/{{ logstash_ssl_key_name }}"
  register: logstash_ssl_key

- name: Copy SSL cert to logstash certs directory
  copy:
    src: "/etc/letsencrypt/live/{{ inventory_hostname|lower }}/fullchain.pem"
    dest: "{{ logstash_certs_dir }}/{{ logstash_ssl_cert_name }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
    remote_src: yes
  when:
    - generateca is not defined or not generateca
    - elasticsearch_https_enabled
    - not logstash_ssl_cert.stat.exists or logstash_ssl_cert.stat.checksum != (lookup('file', logstash_certs_dir + "/" + logstash_ssl_cert_name) | hash('sha256'))

- name: Copy SSL key to logstash certs directory
  copy:
    src: "/etc/letsencrypt/live/{{ inventory_hostname|lower }}/privkey.pem"
    dest: "{{ logstash_certs_dir }}/{{ logstash_ssl_key_name }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0600
    remote_src: yes
  when:
    - generateca is not defined or not generateca
    - elasticsearch_https_enabled
    - not logstash_ssl_key.stat.exists or logstash_ssl_key.stat.checksum != (lookup('file', logstash_certs_dir + "/" + logstash_ssl_key_name) | hash('sha256'))

- set_fact:
    elastic_virtual_proto: "{{ 'https' if elasticsearch_https_enabled else 'http' }}"

- name: Set a flag if Logstash version is greater than or equal to 8.9.0
  set_fact:
    use_new_ssl_setting: "{{ logstash_version is version('8.9.0', '>=') }}"

- name: Render logstash yml configuration file
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: "{{ logstash_conf_dir }}/logstash.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - check if logstash is active
    - restart logstash

- set_fact:
    this_role_path: "{{ role_path }}"

- name: Synchronize templated configuration files to the final destination
  import_role:
    name: utils
    tasks_from: sync_directories.yml
  vars:
    src_conf_dir: "{{ this_role_path }}/templates/configs/pipelines/"
    dest_conf_dir: "{{ logstash_conf_dir }}/conf.d/pipelines/"
    src_extension: ".conf.j2"
    dest_extension: ".conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  notify:
    - check if logstash is active
    - restart logstash

- name: Synchronize templated pattern files to the final destination
  import_role:
    name: utils
    tasks_from: sync_directories.yml
  vars:
    src_conf_dir: "{{ this_role_path }}/templates/patterns/"
    dest_conf_dir: "{{ logstash_conf_dir }}/patterns/"
    src_extension: ".txt.j2"
    dest_extension: ".txt"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  notify:
    - check if logstash is active
    - restart logstash

- name: Synchronize logstash script files to the final destination
  import_role:
    name: utils
    tasks_from: sync_directories.yml
  vars:
    src_conf_dir: "{{ this_role_path }}/templates/scripts/"
    dest_conf_dir: "{{ logstash_conf_dir }}/scripts/"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  notify:
    - check if logstash is active
    - restart logstash

- name: Generate Logstash pipelines.yml
  template:
    src: pipelines.yml.j2
    dest: "{{ logstash_conf_dir }}/pipelines.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - check if logstash is active
    - restart logstash

- name: Include step-client role
  include_role:
    name: step-client
  when: logstash_mqtt_client_mtls

- name: ensure expect package is present
  ansible.builtin.package:
    name: expect
    state: present

- name: Render logstash JVM configuration file
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "{{ logstash_conf_dir }}/jvm.options"
    owner: "{{logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - check if logstash is active
    - restart logstash

- name: Copy logstash log4j configuration file
  ansible.builtin.copy:
    src: log4j2.properties
    dest: "{{ logstash_conf_dir }}/log4j2.properties"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  notify:
    - check if logstash is active
    - restart logstash

- name: Check if Logstash plugins are installed
  command: /opt/logstash/bin/logstash-plugin list
  register: installed_plugins
  changed_when: false

- name: Install Logstash plugins
  command: "/opt/logstash/bin/logstash-plugin install {{ item }}"
  loop:
    - logstash-input-paho-mqtt
    - logstash-filter-elapsed
  when: "item not in installed_plugins.stdout_lines"
  notify:
    - check if logstash is active
    - restart logstash