---
- name: keystore exists
  stat:
    path: "{{ logstash_conf_dir }}/logstash.keystore"
  register: keystore_file

- name: generate setup_keystore utils script
  ansible.builtin.template:
    src: setup_keystore.sh.j2
    dest: "/usr/local/sbin/setup_keystore.sh"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0700

- name: render password file
  ansible.builtin.template:
    src: password_file.txt.j2
    dest: /tmp/password_file.txt
    mode: 0400
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
  # when: not keystore_file.stat.exists

- name: Create logstash keystore
  ansible.builtin.command: >
    su - {{ logstash_user }} -c /usr/local/sbin/setup_keystore.sh
  # when: not keystore_file.stat.exists

- name: Remove password file
  ansible.builtin.file:
    path: /tmp/password_file.txt
    state: absent