---
- hosts: elasticsearch
  become: yes
  #remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - elasticsearch
  tasks:
    - name: Set elasticsearch_hosts variable based on inventory
      set_fact:
        elasticsearch_hosts: "{{ groups['elasticsearch'] }}"
      when:
        - "elasticsearch_hosts is not defined"
    - import_role:
        name: elasticsearch

- hosts: kibana
  become: yes
  #remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - kibana
  tasks:
    - name: Set elasticsearch_hosts variable based on inventory
      set_fact:
        elasticsearch_hosts: "{{ groups['elasticsearch'] }}"
      when:
        - "elasticsearch_hosts is not defined"
    - import_role:
        name: kibana
    - import_role:
        name: nginx
      when: kibana_use_nginx_proxy

- hosts: logstash
  become: yes
  #remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - logstash
  tasks:
    - name: Set elasticsearch_hosts variable based on inventory
      set_fact:
        elasticsearch_hosts: "{{ groups['elasticsearch'] }}"
      when:
        - "elasticsearch_hosts is not defined"
    - import_role:
        name: logstash

- hosts: elasticsearch
  become: yes
  #remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - beats
  tasks:
    - name: Set elasticsearch_hosts variable based on inventory
      set_fact:
        elasticsearch_hosts: "{{ groups['elasticsearch'] }}"
      when:
        - "elasticsearch_hosts is not defined"
    - import_role:
        name: beats
