---
- hosts: elasticsearch
  become: yes
  remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - elasticsearch
  tasks:
    - name: Set elasticsearch_hosts variable based on inventory
      set_fact:
        elasticsearch_hosts: "{{ groups['elasticsearch'] }}"
    - import_role:
        name: elasticsearch

- hosts: kibana
  become: yes
  remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - kibana
  tasks:
    - import_role:
        name: kibana

- hosts: logstash
  become: yes
  remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - logstash
  tasks:
    - import_role:
        name: logstash

- hosts: elasticsearch
  become: yes
  remote_user: vagrant
  vars_files:
    - vars.yml
    - secrets.yml
  tags:
    - beats
  tasks:
    - import_role:
        name: beats
