---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: check if logstash is active
  command: systemctl is-active logstash
  register: logstash_check
  changed_when: false
  ignore_errors: true

- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
  when: logstash_check.rc == 0  # rc (return code) is 0 when the service is active