- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: check if elasticsearch is active
  command: systemctl is-active elasticsearch
  register: elasticsearch_check
  changed_when: false
  ignore_errors: true

- name: restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
  when: elasticsearch_check.rc == 0  # rc (return code) is 0 when the service is active