- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
  when: ansible.builtin.systemd.get_unit_state('elasticsearch').ActiveState == 'active'
