- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart elasticsearch
  block:
    - name: Check if Kibana is active
      command: systemctl is-active elasticsearch
      register: elasticsearch_check
      changed_when: false
      ignore_errors: true

    - name: Actually restart Elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        state: restarted
      when: elasticsearch_check.rc == 0  # rc (return code) is 0 when the service is active