- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: check if kibana is active
  command: systemctl is-active kibana
  register: kibana_check
  changed_when: false
  ignore_errors: true

- name: restart kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  when: kibana_check.rc == 0 and kibana_service is defined and not kibana_service.changed # rc (return code) is 0 when the service is active
  
- name: wait kibana to be ready
  ansible.builtin.uri:
    url: "{{ kibana_virtual_proto }}://localhost:{{ kibana_port }}"
    status_code: 200
    follow_redirects: safe
  register: result
  until: result.status == 200
  retries: 30
  delay: 20