- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  when: ansible.builtin.systemd.get_unit_state('kibana').ActiveState == 'active'