---

- set_fact:
    virtual_proto: "{{ 'https' if elasticsearch_https_enabled else 'http' }}"

- name: reload elasticsearch config after change
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
  when: elastic_config.changed

- name: enable and start elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch 
    state: started 
    enabled: yes
  register: elastic_service

- debug: var=inventory_hostname
- debug: var=ansible_host

- name: wait elasticsearch to be ready
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://{{ ansible_host | default(inventory_hostname) }}:{{ elasticsearch_http_port }}"
    status_code: 200
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: GET
    force_basic_auth: yes
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 30
  delay: 20
