---
- name: keystore exists
  stat:
    path: "{{ elasticsearch_conf_dir }}/elasticsearch.keystore"
  register: keystore_file

- name: generate setup_keystore utils script
  ansible.builtin.template:
    src: setup_keystore.sh.j2
    dest: "/usr/local/sbin/elastic_setup_keystore.sh"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0700

- name: render password file
  ansible.builtin.template:
    src: password_file.txt.j2
    dest: /tmp/elastic_password_file.txt
    mode: 0400
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  changed_when: false
  # when: not keystore_file.stat.exists

- name: Create elastic keystore
  ansible.builtin.command: >
    su - {{ elasticsearch_user }} -c /usr/local/sbin/elastic_setup_keystore.sh
  register: keystore_result
  changed_when: keystore_result.rc == 1
  failed_when: keystore_result.rc not in [0, 1]
  notify:
    - check if elasticsearch is active
    - restart elasticsearch
    - wait elasticsearch to be ready

- name: Remove password file
  ansible.builtin.file:
    path: /tmp/elastic_password_file.txt
    state: absent
  changed_when: false