---
- setup:

- include_tasks: 
    file: preflight.yml

- include_tasks: 
    file: setup_hosts.yml
    apply:
      tags: elkhosts,elasticsearch
  tags: elkhosts,elasticsearch
  when: elasticsearch_resolv_mode == 'hosts'

- include_tasks: 
    file: install_elasticsearch.yml
    apply:
      tags: elkinstall,elasticsearch
  tags: elkinstall,elasticsearch

- include_tasks: 
    file: enable_elasticsearch.yml
    apply:
      tags: elkenable,elasticsearch
  tags: elkenable,elasticsearch

- include_tasks: 
    file: setup_elastic_users.yml
    apply:
      tags: elkusers,elasticsearch
  tags: elkusers,elasticsearch
  when: elasticsearch_security_enabled

- include_tasks: "{{ item }}"
  loop:
    - setup_ingest_pipelines.yml
    - setup_index_templates.yml
    - setup_transforms.yml
    - setup_index_lifecycles.yml
    - setup_index_aliases.yml
  tags: elkindexes,elasticsearch
  when: inventory_hostname in groups['primary_http_host']