---

- name: Install certbot (Debian-based systems)
  ansible.builtin.apt:
    name: certbot
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Install certbot (RedHat-based systems)
  ansible.builtin.yum:
    name: certbot
    state: present
  when: ansible_os_family == 'RedHat'
  become: true

- name: Request HTTPS certificate for each elasticsearch host
  ansible.builtin.command:
    cmd: "certbot certonly --standalone -d {{ item }} --register-unsafely-without-email --agree-tos"
  loop: "{{ elasticsearch_hosts }}"
  become: true

- name: Create PKCS12 file for each elasticsearch host
  ansible.builtin.command:
    cmd: > 
      openssl pkcs12 -export 
      -in /etc/letsencrypt/live/{{ item }}/fullchain.pem
      -inkey /etc/letsencrypt/live/{{ item }}/privkey.pem
      -out /tmp/{{ item }}.p12
      -name elasticsearch -passout pass:{{ elasticsearch_cert_password }}
  loop: "{{ elasticsearch_hosts }}"
  become: true

- name: Copy the PKCS12 file to Elasticsearch certs directory
  ansible.builtin.copy:
    src: "/tmp/{{ item }}.p12"
    dest: "{{ elasticsearch_certs_dir }}/{{ item }}.p12"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644
  loop: "{{ elasticsearch_hosts }}"
  become: true

- name: Clean up temporary PKCS12 files
  ansible.builtin.file:
    path: "/tmp/{{ item }}.p12"
    state: absent
  loop: "{{ elasticsearch_hosts }}"
  become: true