- name: Execute index templates
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://localhost:9200/_index_template/{{ item | basename | regex_replace('\\.json$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/files/index-templates/*.json"
  run_once: true