- name: Execute ingest pipelines
  ansible.builtin.uri:
    url: "{{ virtual_proto }}:{{ elasticsearch_http_port }}/_ingest/pipeline/{{ ingest_pipeline_item | basename | regex_replace('\\.json\\.j2$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', ingest_pipeline_item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/templates/ingest-pipelines/*.json.j2"
  loop_control:
    loop_var: ingest_pipeline_item
  run_once: true
  delegate_to: localhost