- name: Execute transforms
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://localhost:9200/_transform/{{ transform_item | basename | regex_replace('\\.json$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', transform_item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/files/transforms/*.json"
  loop_control:
    loop_var: transform_item
  run_once: true