- name: Execute index lifecycle policy
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://{{ inventory_hostname }}:{{ elasticsearch_http_port }}/_ilm/policy/{{ index_lifecycle_item | basename | regex_replace('\\.json\\.j2$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', index_lifecycle_item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/templates/index-lifecycles/*.json.j2"
  loop_control:
    loop_var: index_lifecycle_item
  run_once: true
  delegate_to: localhost