- name: Check if transform exists
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://localhost:9200/_transform/{{ transform_item | basename | regex_replace('\\.json$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: GET
    force_basic_auth: yes
    validate_certs: no
    status_code: [200, 404]  # 200 if exists, 404 if not
  register: transform_check
  loop_control:
    loop_var: transform_item
  with_fileglob:
    - "{{ role_path }}/files/transforms/*.json"
  run_once: true

- name: Create transforms
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://localhost:9200/_transform/{{ transform_result.transform_item | basename | regex_replace('\\.json$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', transform_result.transform_item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  when: transform_result.status == 404  # Replace with a condition that makes sense for your use case
  loop: "{{ transform_check.results }}"
  loop_control:
    loop_var: transform_result
