- name: Execute index templates
  ansible.builtin.uri:
    url: "{{ virtual_proto }}://localhost:9200/_index_template/{{ index_template_item | basename | regex_replace('\\.json\\.j2$', '') }}"
    user: elastic
    password: "{{ elasticsearch_users['elastic']['password'] }}"
    method: PUT
    body: "{{ lookup('template', index_template_item) }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_fileglob:
    - "{{ role_path }}/templates/index-templates/*.json.j2"
  loop_control:
    loop_var: index_template_item
  delegate_to: localhost